export const HTML_TAILWIND_CLASSES = [
  "block",
  "flex",
  "grid",
  "inline-flex",
  "flex-col",
  "flex-wrap",
  "items-center",
  "justify-between",
  "justify-center",
  "grid-cols-1",
  "grid-cols-2",
  "grid-cols-3",
  "gap-2",
  "gap-3",
  "gap-4",
  "gap-6",
  "p-2",
  "p-3",
  "p-4",
  "p-6",
  "px-3",
  "px-4",
  "py-2",
  "py-3",
  "m-0",
  "mt-2",
  "mt-4",
  "mb-2",
  "mb-4",
  "w-full",
  "max-w-prose",
  "max-w-2xl",
  "text-xs",
  "text-sm",
  "text-base",
  "text-lg",
  "text-xl",
  "text-2xl",
  "font-medium",
  "font-semibold",
  "font-bold",
  "leading-relaxed",
  "text-left",
  "text-center",
  "text-right",
  "text-legion-ink",
  "text-legion-muted",
  "text-legion-cyan",
  "bg-legion-paper",
  "bg-legion-ink",
  "bg-legion-cyan",
  "border",
  "border-2",
  "border-legion-line",
  "rounded",
  "rounded-box",
  "overflow-x-auto",
  "table",
  "table-zebra",
] as const;

export const HTML_DAISY_COMPONENTS = ["alert", "badge", "btn", "card", "stat", "table"] as const;

export const HTML_STYLE_CLASSES = [...HTML_TAILWIND_CLASSES, ...HTML_DAISY_COMPONENTS] as const;
