export const HTML_TAILWIND_CLASSES = [
  "block",
  "flex",
  "grid",
  "inline-flex",
  "flex-col",
  "flex-wrap",
  "items-center",
  "justify-between",
  "justify-center",
  "grid-cols-1",
  "grid-cols-2",
  "grid-cols-3",
  "gap-2",
  "gap-3",
  "gap-4",
  "gap-6",
  "p-2",
  "p-3",
  "p-4",
  "p-6",
  "px-3",
  "px-4",
  "py-2",
  "py-3",
  "m-0",
  "mt-2",
  "mt-4",
  "mb-2",
  "mb-4",
  "w-full",
  "max-w-prose",
  "max-w-2xl",
  "text-xs",
  "text-sm",
  "text-base",
  "text-lg",
  "text-xl",
  "text-2xl",
  "font-medium",
  "font-semibold",
  "font-bold",
  "leading-relaxed",
  "text-left",
  "text-center",
  "text-right",
  "text-legion-ink",
  "text-legion-muted",
  "text-legion-cyan",
  "bg-legion-paper",
  "bg-legion-ink",
  "bg-legion-cyan",
  "border",
  "border-2",
  "border-legion-line",
  "rounded",
  "rounded-box",
  "overflow-x-auto",
  "table",
  "table-zebra",
] as const;

export const HTML_DAISY_COMPONENTS = ["alert", "badge", "btn", "card", "stat", "table"] as const;

const HTML_DAISY_BUILD_COMPONENT_CLASSES = [
  "alert",
  "aura",
  "avatar",
  "badge",
  "breadcrumbs",
  "btn",
  "calendar",
  "card",
  "carousel",
  "chat",
  "checkbox",
  "collapse",
  "countdown",
  "diff",
  "divider",
  "dock",
  "drawer",
  "dropdown",
  "fab",
  "fieldset",
  "file-input",
  "filter",
  "footer",
  "hero",
  "hover-3d",
  "hover-gallery",
  "indicator",
  "input",
  "kbd",
  "label",
  "link",
  "list",
  "loading",
  "mask",
  "mega-menu",
  "menu",
  "mockup-browser",
  "modal",
  "navbar",
  "input-otp",
  "progress",
  "radial-progress",
  "radio",
  "range",
  "rating",
  "select",
  "skeleton",
  "stack",
  "stat",
  "stats",
  "status",
  "steps",
  "swap",
  "tab",
  "table",
  "textarea",
  "text-rotate",
  "timeline",
  "toast",
  "toggle",
  "tooltip",
  "validator",
] as const;

const SPACING_VALUES = [
  "0",
  "0.5",
  "1",
  "1.5",
  "2",
  "2.5",
  "3",
  "3.5",
  "4",
  "5",
  "6",
  "7",
  "8",
  "9",
  "10",
  "11",
  "12",
  "14",
  "16",
] as const;

const SPACING_PREFIXES = [
  "p",
  "px",
  "py",
  "pt",
  "pr",
  "pb",
  "pl",
  "m",
  "mx",
  "my",
  "mt",
  "mr",
  "mb",
  "ml",
  "gap",
  "gap-x",
  "gap-y",
] as const;

const SEMANTIC_COLORS = [
  "base-100",
  "base-200",
  "base-300",
  "base-content",
  "primary",
  "primary-content",
  "secondary",
  "secondary-content",
  "accent",
  "accent-content",
  "neutral",
  "neutral-content",
  "info",
  "info-content",
  "success",
  "success-content",
  "warning",
  "warning-content",
  "error",
  "error-content",
] as const;

const STANDARD_COLORS = [
  "slate-300",
  "slate-500",
  "slate-700",
  "gray-300",
  "gray-500",
  "gray-700",
  "blue-300",
  "blue-500",
  "blue-700",
  "green-300",
  "green-500",
  "green-700",
  "amber-300",
  "amber-500",
  "amber-700",
  "red-300",
  "red-500",
  "red-700",
  "white",
  "black",
] as const;

const DAISY_COLOR_VARIANTS = [
  "primary",
  "secondary",
  "accent",
  "neutral",
  "info",
  "success",
  "warning",
  "error",
] as const;

const DAISY_COLOR_COMPONENTS = ["alert", "badge", "btn", "checkbox", "radio", "toggle"] as const;

const DAISY_VARIANTS = [
  "alert-soft",
  "alert-outline",
  "alert-vertical",
  "alert-horizontal",
  "badge-outline",
  "badge-dash",
  "badge-soft",
  "badge-ghost",
  "badge-xs",
  "badge-sm",
  "badge-md",
  "badge-lg",
  "badge-xl",
  "btn-outline",
  "btn-dash",
  "btn-soft",
  "btn-ghost",
  "btn-link",
  "btn-active",
  "btn-xs",
  "btn-sm",
  "btn-md",
  "btn-lg",
  "btn-xl",
  "card-border",
  "card-dash",
  "card-xs",
  "card-sm",
  "card-md",
  "card-lg",
  "card-xl",
  "stats-horizontal",
  "stats-vertical",
  "table-zebra",
  "table-pin-rows",
  "table-pin-cols",
  "table-xs",
  "table-sm",
  "table-md",
  "table-lg",
  "table-xl",
] as const;

export const HTML_TAILWIND_BUILD_CLASSES = [
  ...HTML_TAILWIND_CLASSES,
  ...HTML_DAISY_BUILD_COMPONENT_CLASSES,
  ...SPACING_PREFIXES.flatMap((prefix) => SPACING_VALUES.map((value) => `${prefix}-${value}`)),
  ...SEMANTIC_COLORS.flatMap((color) => [`bg-${color}`, `text-${color}`, `border-${color}`]),
  ...STANDARD_COLORS.flatMap((color) => [`bg-${color}`, `text-${color}`, `border-${color}`]),
  ...DAISY_COLOR_COMPONENTS.flatMap((component) =>
    DAISY_COLOR_VARIANTS.map((variant) => `${component}-${variant}`),
  ),
  ...DAISY_VARIANTS,
  "hidden",
  "inline-block",
  "inline-grid",
  "flex-row",
  "flex-1",
  "flex-none",
  "grow",
  "shrink-0",
  "items-start",
  "items-end",
  "justify-start",
  "justify-end",
  "justify-around",
  "justify-evenly",
  "content-start",
  "content-center",
  "self-start",
  "self-center",
  "self-end",
  "grid-cols-4",
  "grid-cols-5",
  "grid-cols-6",
  "col-span-2",
  "col-span-3",
  "col-span-full",
  "w-auto",
  "w-1/2",
  "w-1/3",
  "w-2/3",
  "w-screen",
  "min-w-0",
  "max-w-none",
  "max-w-sm",
  "max-w-md",
  "max-w-lg",
  "max-w-xl",
  "max-w-3xl",
  "h-auto",
  "h-full",
  "min-h-screen",
  "text-3xl",
  "text-4xl",
  "font-normal",
  "font-extrabold",
  "leading-tight",
  "leading-normal",
  "uppercase",
  "lowercase",
  "tracking-wide",
  "shadow",
  "shadow-sm",
  "shadow-md",
  "shadow-lg",
  "rounded-sm",
  "rounded-md",
  "rounded-lg",
  "rounded-xl",
  "rounded-full",
  "overflow-auto",
  "overflow-hidden",
  "overflow-y-auto",
] as const;

export const HTML_STYLE_CLASSES_DISTINCT = [
  ...new Set<string>([...HTML_TAILWIND_CLASSES, ...HTML_DAISY_COMPONENTS]),
] as const;

export const HTML_STYLE_CLASSES = [...HTML_TAILWIND_CLASSES, ...HTML_DAISY_COMPONENTS] as const;
